// TP3_Agent_Logique.cpp : définit le point d'entrée de l'application.
//

#include "TP3_Agent_Logique.h"
#include "Forest.h"
#include "Rule.h"
#include "Agent.h"

using namespace std;

int main()
{
	//Rule R0 = Rule("HAUT=MONSTRE_PROCHE OU BAS=MONSTRE_PROCHE OU GAUCHE=MONSTRE_PROCHE OU DROITE=MONSTRE_PROCHE OU HAUT_GAUCHE=MONSTRE_PROCHE OU HAUT_DROITE=MONSTRE_PROCHE OU BAS_GAUCHE=MONSTRE_PROCHE OU BAS_DROITE=MONSTRE_PROCHE", "MONSTRE_PROBABLE");
	Rule R1 = Rule("HAUT=MONSTRE_PROCHE ET POSITION=INCONNU", "MONSTRE_PROBABLE");
	Rule R2 = Rule("BAS=MONSTRE_PROCHE ET POSITION=INCONNU", "MONSTRE_PROBABLE");
	Rule R3 = Rule("GAUCHE=MONSTRE_PROCHE ET POSITION=INCONNU", "MONSTRE_PROBABLE");
	Rule R4 = Rule("DROITE=MONSTRE_PROCHE ET POSITION=INCONNU", "MONSTRE_PROBABLE");
	Rule R5 = Rule("HAUT_GAUCHE=MONSTRE_PROCHE ET POSITION=INCONNU", "MONSTRE_PROBABLE");
	Rule R6 = Rule("HAUT_DROITE=MONSTRE_PROCHE ET POSITION=INCONNU", "MONSTRE_PROBABLE");
	Rule R7 = Rule("BAS_GAUCHE=MONSTRE_PROCHE ET POSITION=INCONNU", "MONSTRE_PROBABLE");
	Rule R8 = Rule("BAS_DROITE=MONSTRE_PROCHE ET POSITION=INCONNU", "MONSTRE_PROBABLE");

	Rule R9 = Rule("HAUT=MONSTRE_PROCHE ET HAUT_GAUCHE=MONSTRE_PROCHE ET HAUT_DROITE=MONSTRE_PROCHE ET GAUCHE=MONSTRE_PROCHE", "MONSTRE");
	Rule R10 = Rule("HAUT=MONSTRE_PROCHE ET HAUT_GAUCHE=MONSTRE_PROCHE ET HAUT_DROITE=MONSTRE_PROCHE ET DROITE=MONSTRE_PROCHE", "MONSTRE");
	Rule R11 = Rule("BAS=MONSTRE_PROCHE ET BAS_GAUCHE=MONSTRE_PROCHE ET BAS_DROITE=MONSTRE_PROCHE ET GAUCHE=MONSTRE_PROCHE", "MONSTRE");
	Rule R12 = Rule("BAS=MONSTRE_PROCHE ET BAS_GAUCHE=MONSTRE_PROCHE ET BAS_DROITE=MONSTRE_PROCHE ET DROITE=MONSTRE_PROCHE", "MONSTRE");
	Rule R13 = Rule("DROITE=MONSTRE_PROCHE ET HAUT_DROITE=MONSTRE_PROCHE ET BAS_DROITE=MONSTRE_PROCHE ET HAUT=MONSTRE_PROCHE", "MONSTRE");
	Rule R14 = Rule("DROITE=MONSTRE_PROCHE ET HAUT_DROITE=MONSTRE_PROCHE ET BAS_DROITE=MONSTRE_PROCHE ET BAS=MONSTRE_PROCHE", "MONSTRE");
	Rule R15 = Rule("GAUCHE=MONSTRE_PROCHE ET HAUT_GAUCHE=MONSTRE_PROCHE ET BAS_GAUCHE=MONSTRE_PROCHE ET HAUT=MONSTRE_PROCHE", "MONSTRE");
	Rule R16 = Rule("GAUCHE=MONSTRE_PROCHE ET HAUT_GAUCHE=MONSTRE_PROCHE ET BAS_GAUCHE=MONSTRE_PROCHE ET BAS=MONSTRE_PROCHE", "MONSTRE");


	vector<Rule> rules;
	//rules.push_back(R0);
	/*rules.push_back(R1);
	rules.push_back(R2);
	rules.push_back(R3);
	rules.push_back(R4);
	rules.push_back(R5);
	rules.push_back(R6);
	rules.push_back(R7);
	rules.push_back(R8);*/
	rules.push_back(R9);
	rules.push_back(R10);
	rules.push_back(R11);
	rules.push_back(R12);
	rules.push_back(R13);
	rules.push_back(R14);
	rules.push_back(R15);
	rules.push_back(R16);

	Forest forest = Forest(3);

	Agent agent = Agent(&forest, rules);

	return 0;
}
